# name: Template - Prod

# on:  
#   pull_request:
#     branches:
#       - main

# jobs:
#   test-n-deploy:

#     runs-on: self-hosted

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js 18.x
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18.x
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run test:unit

#     - name: Configure SSH
#       run: |
#         mkdir -p ~/.ssh/
#         echo "$SSH_PRIVATE_KEY" > ~/.ssh/staging
#         chmod 600 ~/.ssh/staging
#         echo "$SSH_KEY" > ~/.ssh/staging.pub
#         chmod 644 ~/.ssh/staging.pub
#         echo -e "Host staging\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/staging\n\tStrictHostKeyChecking no" > ~/.ssh/config
#       env:
#         SSH_USER: ${{ secrets.USER_PROD }}
#         SSH_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
#         SSH_HOST: ${{ secrets.HOST_PROD }}
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#     - name: Cat config
#       run: cat ~/.ssh/config

#     - run: npm run build-only

#     - name: Cat dist
#       run: ls dist

#     - name: Send build files
#       run: rsync -a dist/ staging:~/web/

#     - name: Copy files to www
#       run: ssh staging 'cd ~/web/ && sudo cp -R ./ /var/www/web/'
